### ISSUE TITLE
Error logging on CVAT

### ISSUE THREAD

**Issue by MauroRibeiroHV** [cvat-ai/cvat#4040]
### My actions before raising this issue
- [X ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour
Log in to CVAT

### Current Behaviour
When making 
POST https://cvat.dev-fpl.hitachi-lumada.io/api/v1/auth/login

Error: Request failed with status code 500. "\n<!doctype html>\n<html lang=\"en\">\n<head>\n  <title>Server Error (500)</title>\n</head>\n<body>\n  <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n"
In the backend logs I get the following:

 ERROR - 2021-12-16 16:40:44,812 - log - Internal Server Error: /api/v1/auth/login
 Traceback (most recent call last):
   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
     response = get_response(request)
   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
     return view_func(*args, **kwargs)
   File "/opt/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
     return self.dispatch(request, *args, **kwargs)
   File "/opt/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
     return bound_method(*args, **kwargs)
   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
     return view(request, *args, **kwargs)
   File "/opt/venv/lib/python3.8/site-packages/rest_auth/views.py", line 49, in dispatch
     return super(LoginView, self).dispatch(*args, **kwargs)
   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
     response = self.handle_exception(exc)
   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
     self.raise_uncaught_exception(exc)
   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
     raise exc
   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 493, in dispatch
     self.initial(request, *args, **kwargs)
   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 412, in initial
     self.check_throttles(request)
   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 355, in check_throttles
     if not throttle.allow_request(request, self):
   File "/opt/venv/lib/python3.8/site-packages/rest_framework/throttling.py", line 123, in allow_request
     self.history = self.cache.get(self.key, [])
   File "/opt/venv/lib/python3.8/site-packages/django/core/cache/__init__.py", line 98, in __getattr__
     return getattr(caches[DEFAULT_CACHE_ALIAS], name)
   File "/opt/venv/lib/python3.8/site-packages/django/core/cache/__init__.py", line 79, in __getitem__
     cache = _create_cache(alias)
   File "/opt/venv/lib/python3.8/site-packages/django/core/cache/__init__.py", line 54, in _create_cache
     return backend_cls(location, params)
   File "/opt/venv/lib/python3.8/site-packages/diskcache/djangocache.py", line 29, in __init__
     self._cache = FanoutCache(directory, shards, timeout, **options)
   File "/opt/venv/lib/python3.8/site-packages/diskcache/fanout.py", line 38, in __init__
     self._shards = tuple(
   File "/opt/venv/lib/python3.8/site-packages/diskcache/fanout.py", line 39, in <genexpr>
     Cache(
   File "/opt/venv/lib/python3.8/site-packages/diskcache/core.py", line 457, in __init__
     sql = self._sql_retry
   File "/opt/venv/lib/python3.8/site-packages/diskcache/core.py", line 649, in _sql_retry
     sql = self._sql
   File "/opt/venv/lib/python3.8/site-packages/diskcache/core.py", line 644, in _sql
     return self._con.execute
   File "/opt/venv/lib/python3.8/site-packages/diskcache/core.py", line 631, in _con
     settings = con.execute(select).fetchall()
 sqlite3.DatabaseError: database disk image is malformed

### Steps to Reproduce (for bugs)
We had multiple users logging in the CVAT and performing annotations

### Context
I was trying to login

### Your Environment
Azure cluster with cvat-backend with 2 replicas

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by azhavoro** [comment]
```
sqlite3.DatabaseError: database disk image is malformed
```
Hi, I suppose this is the reason
How did you set up the sharing of the sqlite database file between replicas?
I would suggest using postgres database anyway.

**Comment by MauroRibeiroHV** [comment]
> ```
> sqlite3.DatabaseError: database disk image is malformed
> ```
> 
> Hi, I suppose this is the reason How did you set up the sharing of the sqlite database file between replicas? I would suggest using postgres database anyway.

Hi,

But the thing is, I'm using postgres

**Comment by azhavoro** [comment]
Oh, sorry I didn't read the full log first, I believe this is a related issue https://github.com/openvinotoolkit/cvat/issues/2793
I currently suggest trying to delete the `cache` folder in `cvat_data` volume. It is possible that discache does not work correctly on many replicas. Try to use only one replica for the backend.

**Comment by azhavoro** [comment]
fixed in https://github.com/cvat-ai/cvat/pull/6773
