### ISSUE TITLE
Could not get models from the server

### ISSUE THREAD

**Issue by bhargav-sudo** [cvat-ai/cvat#51]
DL model are running successfully but this is the error i get.

![Screenshot from 2022-07-26 20-48-04](https://user-images.githubusercontent.com/57169077/181044801-2eb0a44a-270d-4806-ad64-f862a5d8f5f7.png)

nuctl get functions
![Screenshot from 2022-07-26 20-46-03](https://user-images.githubusercontent.com/57169077/181044884-7e427803-deb2-4c00-bbaa-71213bba20b3.png)

Here are the docker logs for CVAT.
[cvat.log](https://github.com/cvat-ai/cvat/files/9191056/cvat.log)

Thanks,

**Comment by bsekachev** [comment]
@bhargav-sudo 

As I can see one function has ``unhealthy`` state. Can you try to delete it and then recheck?

**Comment by bsekachev** [comment]
From stack trace you sent we can see followings:

```
[Tue Jul 26 15:06:13.231015 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772] Traceback (most recent call last):
[Tue Jul 26 15:06:13.231016 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Tue Jul 26 15:06:13.231017 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     response = get_response(request)
[Tue Jul 26 15:06:13.231019 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Tue Jul 26 15:06:13.231020 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Jul 26 15:06:13.231021 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Tue Jul 26 15:06:13.231023 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     return view_func(*args, **kwargs)
[Tue Jul 26 15:06:13.231024 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
[Tue Jul 26 15:06:13.231025 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     return self.dispatch(request, *args, **kwargs)
[Tue Jul 26 15:06:13.231026 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
[Tue Jul 26 15:06:13.231028 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     response = self.handle_exception(exc)
[Tue Jul 26 15:06:13.231029 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
[Tue Jul 26 15:06:13.231030 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     self.raise_uncaught_exception(exc)
[Tue Jul 26 15:06:13.231031 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Tue Jul 26 15:06:13.231033 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     raise exc
[Tue Jul 26 15:06:13.231034 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
[Tue Jul 26 15:06:13.231035 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     response = handler(request, *args, **kwargs)
[Tue Jul 26 15:06:13.231036 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/home/django/cvat/apps/lambda_manager/views.py", line 608, in func_wrapper
[Tue Jul 26 15:06:13.231038 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     data = func(*args, **kwargs)
[Tue Jul 26 15:06:13.231039 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/home/django/cvat/apps/lambda_manager/views.py", line 652, in list
[Tue Jul 26 15:06:13.231040 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     return [f.to_dict() for f in gateway.list()]
[Tue Jul 26 15:06:13.231042 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/home/django/cvat/apps/lambda_manager/views.py", line 69, in list
[Tue Jul 26 15:06:13.231044 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     response = [LambdaFunction(self, item) for item in data.values()]
[Tue Jul 26 15:06:13.231045 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/home/django/cvat/apps/lambda_manager/views.py", line 69, in <listcomp>
[Tue Jul 26 15:06:13.231046 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     response = [LambdaFunction(self, item) for item in data.values()]
[Tue Jul 26 15:06:13.231048 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/home/django/cvat/apps/lambda_manager/views.py", line 102, in __init__
[Tue Jul 26 15:06:13.231049 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     spec = json.loads(meta_anno.get('spec') or '[]')
[Tue Jul 26 15:06:13.231050 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
[Tue Jul 26 15:06:13.231051 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     return _default_decoder.decode(s)
[Tue Jul 26 15:06:13.231053 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
[Tue Jul 26 15:06:13.231054 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[Tue Jul 26 15:06:13.231056 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]   File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
[Tue Jul 26 15:06:13.231058 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772]     obj, end = self.scan_once(s, idx)
[Tue Jul 26 15:06:13.231060 2022] [wsgi:error] [pid 473:tid 140374830491392] [remote 172.18.0.3:45772] json.decoder.JSONDecodeError: Invalid control character at: line 2 column 30 (char 31)
```

Exactly line:
``spec = json.loads(meta_anno.get('spec') or '[]')``
says that serverless function ``spec`` can not be decoded because it is not JSON. Can you please check it in corresponding ``function.yaml`` files?

**Comment by bhargav-sudo** [comment]
ok @bsekachev I will try that and let you know.

**Comment by bhargav-sudo** [comment]
> @bhargav-sudo
> 
> As I can see one function has `unhealthy` state. Can you try to delete it and then recheck?

@bsekachev I am facing this issue while I am Opening the CVAT tool itself.

**Comment by bhargav-sudo** [comment]
@bsekachev working now.
Thanks
