### ISSUE TITLE
CVAT fails health check using >90% disk

### ISSUE THREAD

**Issue by harrystuart** [cvat-ai/cvat#5449]
### My actions before raising this issue
Clone latest develop.
`docker-compose -f docker-compose.yml -f docker-compose.dev.yml build`
`docker-compose up -d`

### Expected Behaviour
Startup and run application.

### Current Behaviour
Computer runs very slowly as CVAT uses significant resources. When trying to login, the following occurs:

`get http://10.0.253.33:9001/api/server/health/?format=json&org=`
`{"Cache backend: default": "working", "DatabaseBackend": "working", "DiskUsage": "warning: 86c1cd71866c 92.4% disk usage exceeds 90%", "MemoryUsage": "working", "MigrationsHealthCheck": "working"}`

Server logs:

```
2022-12-12 04:54:32,063 DEBG 'runserver' stderr output:
[Mon Dec 12 04:54:32.063061 2022] [wsgi:error] [pid 178:tid 139765320791808] ERROR:health-check:warning: 35a75041c750 92.4% disk usage exceeds 90%
[Mon Dec 12 04:54:32.063076 2022] [wsgi:error] [pid 178:tid 139765320791808] Traceback (most recent call last):
[Mon Dec 12 04:54:32.063085 2022] [wsgi:error] [pid 178:tid 139765320791808]   File "/opt/venv/lib/python3.8/site-packages/health_check/backends.py", line 30, in run_check

2022-12-12 04:54:32,063 DEBG 'runserver' stderr output:
[Mon Dec 12 04:54:32.063125 2022] [wsgi:error] [pid 178:tid 139765320791808]     self.check_status()

2022-12-12 04:54:32,063 DEBG 'runserver' stderr output:
[Mon Dec 12 04:54:32.063420 2022] [wsgi:error] [pid 178:tid 139765320791808]   File "/opt/venv/lib/python3.8/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
[Mon Dec 12 04:54:32.063422 2022] [wsgi:error] [pid 178:tid 139765320791808]     raise ServiceWarning(
[Mon Dec 12 04:54:32.063422 2022] [wsgi:error] [pid 178:tid 139765320791808] health_check.exceptions.ServiceWarning: warning: 35a75041c750 92.4% disk usage exceeds 90%

2022-12-12 04:54:32,082 DEBG 'runserver' stderr output:
[Mon Dec 12 04:54:32.082022 2022] [wsgi:error] [pid 178:tid 139767587452672] [remote 172.27.0.4:39110] [2022-12-12 04:54:32,081] ERROR django.request: Internal Server Error: /api/server/health/
[Mon Dec 12 04:54:32.082094 2022] [wsgi:error] [pid 178:tid 139767587452672] [remote 172.27.0.4:39110] ERROR:django.request:Internal Server Error: /api/server/health/
```

**Comment by nmanovic** [comment]
@harrystuart , you can adjust health check limits (https://github.com/revsys/django-health-check/blob/master/health_check/conf.py)

Please try to define in cvat/settings/base.py the following variable:

```
HEALTH_CHECK = {
    "DISK_USAGE_MAX": 99
}
```

**Comment by harrystuart** [comment]
Does it sound right for CVAT to be using so much in the first place? I
don’t recall it being so consuming.

**Comment by nmanovic** [comment]
Need to investigate why it consumes so many resources. I agree, it isn't right.

**Comment by Ghaitharar** [comment]
Any update on this?

I used CVAT on windows 10 to annotated a number of .mp4 videos that are collectively less than 1GB in size. When trying to extract the dataset, CVAT consumes more than 100GB and then report "OS Error: [Errno 28] No space left on device\n/". 

Could it be related to image compression level of the tasks?

![image](https://user-images.githubusercontent.com/54161236/208956005-9c4268e6-cdba-4f96-bf68-26c6e23cc8fc.png)

**Comment by zhiltsov-max** [comment]
@harrystuart, @Harsturomai, @Ghaitharar, hi, could you please share and check the output of the following commands in the terminal:

```bash
docker exec -it -u django cvat_server python -c 'import os; print(os.statvfs("/"))'
docker exec -it -u django cvat_server python -c 'import psutil; print(psutil.disk_usage("/"))'
docker exec -it -u django cvat_server df -h /
```

> I used CVAT on windows 10 to annotated a number of .mp4 videos that are collectively less than 1GB in size. When trying to extract the dataset, CVAT consumes more than 100GB and then report

@Ghaitharar, it can be related to video frame unpacking. If I understand correctly, you're trying to export a task with images. In this case the video images will be saved on disk and then packed into an archive. If you're exporting a task, please try to turn off the `Save images` option. 

In general, I see few ways to handle the problem:
- export just annotations, turn the `Save images` checkbox off
  ![image](https://user-images.githubusercontent.com/13832349/208958725-73043e10-6aaf-455d-990e-b2f804c8f10c.png)
- turn off the `use chunks` switch during task creation
  ![image](https://user-images.githubusercontent.com/13832349/208958978-498d4c69-6d54-4478-86de-c5924831eed3.png)
- check for the exported dataset cache and clean it with this command: 
  ```bash
  docker exec -it cvat_server bash -c 'rm -r data/*/*/export_cache/'
  ``` 
  (if you see `rm: cannot remove 'data/*/*/export_cache/': No such file or directory`, everything is OK)
- try to clear the cache with this command:
  ```bash
  docker exec -it cvat_server bash -c 'rm -r data/cache/'
  ``` 
- turn off the use cache checkbox (note that this may slow down the workflow with videos)

**Comment by Ghaitharar** [comment]
@zhiltsov-max

`os.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=65793553, f_bfree=40155087, f_bavail=36795548, f_files=16777216, f_ffree=16686506, f_favail=16686506, f_flag=4096, f_namemax=255)`

`sdiskusage(total=269490393088, used=105015156736, free=150714564608, percent=41.1)`

`Filesystem      Size  Used Avail Use% Mounted on

overlay         251G   98G  141G  42% /`

**Comment by zhiltsov-max** [comment]
> Is there a way to turn off use chunks after a task is created? I'v already created a number of tasks with this option enabled.

Unfortunately, no. I can suggest you to export the annotations without images, and then you can download images separately using SDK or CLI: `cvat-cli frames --quality original --outdir task_<N>_images <task_id>` (modify the command to fit your case).

**Comment by wegmatho** [comment]
> HEALTH_CHECK = {
>     "DISK_USAGE_MAX": 99
> }

Are these settings somehow injectable without backing a new cvat docker image? 
I am "suffering" from the same issue, since my K8s nodes have little disk space, thus running into the limit preventing the webserver to start, even though cvat-backend-data volume is placed on another machine via nfs volume and has plenty space.

**Comment by harrystuart** [comment]
Hi all, I will be away from my computer until the 6th of Jan. Even if a resolution is found, may I please ask that this issue is not closed until I can test? Much appreciated

**Comment by nmanovic** [comment]
- [ ] Need to add into documentation more information about health check and its configuration
- [ ] Need to fix creation of tasks with video files. By default, they are created with zip chunks with images

**Comment by ksaluja15** [comment]
@nmanovic I added the health check variable, but somehow it's not being used when I relaunch with the docker compose command. any idea ?

**Comment by pwichmann** [comment]
I have the same problem. Cannot get CVAT to run. What a shame since Label Studio sucks, too.

**Comment by pwichmann** [comment]
CVAT needed more than 70 GB of free disk space on my machine. I gave it 280 GB of free space now and it is running. Note: I just installed it. This were the disk needs before any labelling.

**Comment by sourabh0207** [comment]
I cleared the cache as mentioned above but maybe due to this I am unable to get analytics, Is anybody facing the same issue?

https://github.com/opencv/cvat/issues/6724

**Comment by Jansen-Lin** [comment]
> @harrystuart, @Harsturomai, @Ghaitharar, hi, could you please share and check the output of the following commands in the terminal:
> 
> ```shell
> docker exec -it -u django cvat_server python -c 'import os; print(os.statvfs("/"))'
> docker exec -it -u django cvat_server python -c 'import psutil; print(psutil.disk_usage("/"))'
> docker exec -it -u django cvat_server df -h /
> ```
> 
> > I used CVAT on windows 10 to annotated a number of .mp4 videos that are collectively less than 1GB in size. When trying to extract the dataset, CVAT consumes more than 100GB and then report
> 
> @Ghaitharar, it can be related to video frame unpacking. If I understand correctly, you're trying to export a task with images. In this case the video images will be saved on disk and then packed into an archive. If you're exporting a task, please try to turn off the `Save images` option.
> 
> In general, I see few ways to handle the problem:
> 
> * export just annotations, turn the `Save images` checkbox off
>   ![image](https://user-images.githubusercontent.com/13832349/208958725-73043e10-6aaf-455d-990e-b2f804c8f10c.png)
> * turn off the `use chunks` switch during task creation
>   ![image](https://user-images.githubusercontent.com/13832349/208958978-498d4c69-6d54-4478-86de-c5924831eed3.png)
> * check for the exported dataset cache and clean it with this command:
>   ```shell
>   docker exec -it cvat_server bash -c 'rm -r data/*/*/export_cache/'
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   (if you see `rm: cannot remove 'data/*/*/export_cache/': No such file or directory`, everything is OK)
> * try to clear the cache with this command:
>   ```shell
>   docker exec -it cvat_server bash -c 'rm -r data/cache/'
>   ```
> * turn off the use cache checkbox (note that this may slow down the workflow with videos)

clearing the data/cache is a bad move

**Comment by stsoor** [comment]
> injectable without baking a new cvat docker image?
> I am "suffering" from the same issue, since my K8s nodes have little disk space, thus running into the limit preventing the webserver to start, even though cvat-backend-d

Easiest way is changing the 
`command: init run server`
to
`entrypoint: sh -c "echo 'HEALTH_CHECK = {\"DISK_USAGE_MAX\":99}' >> /home/django/cvat/settings/base.py && exec ./backend_entrypoint.sh init run server`
for the cvat_server service in docker-compose.yml. This will basically change the in-docker settings file before starting the service with the same command as before.

**Comment by pimakshay** [comment]
> Easiest way is changing the `command: init run server` to `entrypoint: sh -c "echo 'HEALTH_CHECK = {\"DISK_USAGE_MAX\":99}' >> /home/django/cvat/settings/base.py && exec ./backend_entrypoint.sh init run server` for the cvat_server service in docker-compose.yml. This will basically change the in-docker settings file before starting the service with the same command as before.

This worked for me. In fact, the easiest solution compared to other suggested solutions.

**Comment by zhiltsov-max** [comment]
I guess we could just make it configurable via an env variable.

**Comment by adiatma85** [comment]
Hello, I am using cvat_server on docker container with this [image](https://hub.docker.com/layers/cvat/server/v2.10.1/images/sha256-f7b558201d8231c88bcf6856e6d9b40dada249830e7e25fe0e8c27e3e530fd9a)

I am agree that the responsbility to clean the disk usage is on the me as the user, but giving a control to override the threshold for health check is great. Because the main problem is CVAT does not return only a warning, but completely unaccessible when this happen

**Comment by ganindu7** [comment]
> * docker exec -it cvat_server bash -c 'rm -r data/cache/'

I tried that and it did not fix the issue, here is the command output.

```
os.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=25656558, f_bfree=2586208, f_bavail=1271392, f_files=6553600, f_ffree=5003768, f_favail=5003768, f_flag=4096, f_namemax=255)
ganindu@gsrv-2:~$ docker exec -it -u django cvat_server python -c 'import psutil; print(psutil.disk_usage("/"))'
sdiskusage(total=105089261568, used=94496452608, free=5207322624, percent=94.8)
ganindu@gsrv-2:~$ docker exec -it -u django cvat_server df -h /
Filesystem      Size  Used Avail Use% Mounted on
overlay          98G   89G  4.9G  95% /
ganindu@gsrv-2:~$ docker exec -it cvat_server bash -c 'rm -r data/*/*/export_cache/'
ganindu@gsrv-2:~$ docker exec -it -u django cvat_server df -h /
Filesystem      Size  Used Avail Use% Mounted on
overlay          98G   89G  4.9G  95% /
ganindu@gsrv-2:~$ docker exec -it cvat_server bash -c 'rm -r data/cache/'
ganindu@gsrv-2:~$ docker exec -it -u django cvat_server df -h /
Filesystem      Size  Used Avail Use% Mounted on
overlay          98G   89G  4.9G  95% /
ganindu@gsrv-2:~$ 


```


The original reason I came here was this in logs and I couldn't access the ui from checking logs on the server I got 

```
...
2025-09-15 11:14:04,258 DEBG 'uvicorn-0' stdout output:
[2025-09-15 11:14:04,257] INFO:     172.18.0.2:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified

2025-09-15 11:14:05,783 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:05,782] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%

2025-09-15 11:14:05,828 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:05,828] ERROR django.request: Internal Server Error: /api/server/health/

2025-09-15 11:14:05,829 DEBG 'uvicorn-0' stdout output:
[2025-09-15 11:14:05,828] INFO:     172.16.22.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2025-09-15 11:14:08,854 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:08,851] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%

2025-09-15 11:14:08,895 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:08,894] ERROR django.request: Internal Server Error: /api/server/health/

2025-09-15 11:14:08,895 DEBG 'uvicorn-0' stdout output:
[2025-09-15 11:14:08,895] INFO:     172.16.22.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2025-09-15 11:14:10,453 DEBG 'uvicorn-0' stdout output:
[2025-09-15 11:14:10,453] INFO:     172.18.0.2:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified

2025-09-15 11:14:11,916 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:11,915] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%

2025-09-15 11:14:11,958 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:11,958] ERROR django.request: Internal Server Error: /api/server/health/

2025-09-15 11:14:11,959 DEBG 'uvicorn-0' stdout output:
[2025-09-15 11:14:11,958] INFO:     172.16.22.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2025-09-15 11:14:14,982 DEBG 'uvicorn-1' stderr output:
[2025-09-15 11:14:14,980] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%

2025-09-15 11:14:15,024 DEBG 'uvicorn-1' stderr output:
[2025-09-15 11:14:15,023] ERROR django.request: Internal Server Error: /api/server/health/

2025-09-15 11:14:15,024 DEBG 'uvicorn-1' stdout output:
[2025-09-15 11:14:15,024] INFO:     172.16.22.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2025-09-15 11:14:18,050 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:18,048] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%

2025-09-15 11:14:18,091 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:18,090] ERROR django.request: Internal Server Error: /api/server/health/

2025-09-15 11:14:18,092 DEBG 'uvicorn-0' stdout output:
[2025-09-15 11:14:18,091] INFO:     172.16.22.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2025-09-15 11:14:20,479 DEBG 'uvicorn-0' stdout output:
[2025-09-15 11:14:20,479] INFO:     172.18.0.2:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified

2025-09-15 11:14:21,114 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:21,113] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%

2025-09-15 11:14:21,147 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:21,147] ERROR django.request: Internal Server Error: /api/server/health/

2025-09-15 11:14:21,148 DEBG 'uvicorn-0' stdout output:
[2025-09-15 11:14:21,147] INFO:     172.16.22.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2025-09-15 11:14:22,257 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:22,255] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%

2025-09-15 11:14:22,300 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:22,299] ERROR django.request: Internal Server Error: /api/server/health/

2025-09-15 11:14:22,301 DEBG 'uvicorn-0' stdout output:
[2025-09-15 11:14:22,300] INFO:     172.16.22.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2025-09-15 11:14:23,227 DEBG 'uvicorn-1' stderr output:
[2025-09-15 11:14:23,226] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%

2025-09-15 11:14:23,264 DEBG 'uvicorn-1' stderr output:
[2025-09-15 11:14:23,263] ERROR django.request: Internal Server Error: /api/server/health/

2025-09-15 11:14:23,264 DEBG 'uvicorn-1' stdout output:
[2025-09-15 11:14:23,264] INFO:     172.16.22.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2025-09-15 11:14:26,283 DEBG 'uvicorn-1' stderr output:
[2025-09-15 11:14:26,281] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%

2025-09-15 11:14:26,325 DEBG 'uvicorn-1' stderr output:
[2025-09-15 11:14:26,325] ERROR django.request: Internal Server Error: /api/server/health/

2025-09-15 11:14:26,326 DEBG 'uvicorn-1' stdout output:
[2025-09-15 11:14:26,326] INFO:     172.16.22.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2025-09-15 11:14:29,345 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:29,345] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%

2025-09-15 11:14:29,390 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:29,389] ERROR django.request: Internal Server Error: /api/server/health/

2025-09-15 11:14:29,391 DEBG 'uvicorn-0' stdout output:
[2025-09-15 11:14:29,390] INFO:     172.16.22.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2025-09-15 11:14:32,416 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:32,413] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%

2025-09-15 11:14:32,456 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:32,456] ERROR django.request: Internal Server Error: /api/server/health/

2025-09-15 11:14:32,457 DEBG 'uvicorn-0' stdout output:
[2025-09-15 11:14:32,457] INFO:     172.16.22.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2025-09-15 11:14:33,777 DEBG 'uvicorn-0' stdout output:
[2025-09-15 11:14:33,777] INFO:     172.18.0.2:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified

2025-09-15 11:14:35,481 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:35,479] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%

2025-09-15 11:14:35,522 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:35,521] ERROR django.request: Internal Server Error: /api/server/health/

2025-09-15 11:14:35,522 DEBG 'uvicorn-0' stdout output:
[2025-09-15 11:14:35,522] INFO:     172.16.22.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2025-09-15 11:14:38,544 DEBG 'uvicorn-1' stderr output:
[2025-09-15 11:14:38,542] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%

2025-09-15 11:14:38,586 DEBG 'uvicorn-1' stderr output:
[2025-09-15 11:14:38,586] ERROR django.request: Internal Server Error: /api/server/health/

2025-09-15 11:14:38,587 DEBG 'uvicorn-1' stdout output:
[2025-09-15 11:14:38,586] INFO:     172.16.22.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2025-09-15 11:14:41,610 DEBG 'uvicorn-1' stderr output:
[2025-09-15 11:14:41,608] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%

2025-09-15 11:14:41,652 DEBG 'uvicorn-1' stderr output:
[2025-09-15 11:14:41,652] ERROR django.request: Internal Server Error: /api/server/health/

2025-09-15 11:14:41,653 DEBG 'uvicorn-1' stdout output:
[2025-09-15 11:14:41,652] INFO:     172.16.22.1:0 - "GET /api/server/health/?format=json&org= HTTP/1.0" 500 Internal Server Error

2025-09-15 11:14:42,888 DEBG 'uvicorn-0' stdout output:
[2025-09-15 11:14:42,888] INFO:     172.18.0.2:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified

2025-09-15 11:14:42,907 DEBG 'uvicorn-0' stderr output:
[2025-09-15 11:14:42,905] ERROR health-check: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/psutil/backends.py", line 21, in check_status
    raise ServiceWarning(f"{host} {du.percent}% disk usage exceeds {DISK_USAGE_MAX}%")
health_check.exceptions.ServiceWarning: warning: bdb7ee288cf8 94.8% disk usage exceeds 90%
...
```

my cvat version 

```
commit dd46f3db6a1c8248fab781805765fc090654492c (tag: v2.42.0, origin/master, tags/v2.42.0, master)
Merge: 183b96c44 72e1e44d1
Author: cvat-bot[bot] <147643061+cvat-bot[bot]@users.noreply.github.com>
Date:   Tue Jul 29 10:29:25 2025 +0000

    Merge pull request #9682 from cvat-ai/release-2.42.0
    
    Release v2.42.0
```

**Comment by skar404** [comment]
Added a new environment flag CVAT_HEALTH_DISK_USAGE_MAX to control the disk usage threshold for the health check.

More details are available in the documentation:
https://docs.cvat.ai/docs/administration/basics/installation/#cvat-health-check-failed-because-of-too-low-free-disk-space
