### ISSUE TITLE
Assertion error on  import of CVAT 1.1 annotation file with tracks

### ISSUE THREAD

**Issue by mikhail-treskin** [cvat-ai/cvat#5638]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)
1. Upload valid annotations file in CVAT 1.1 format (since annotation files on which the issue reproducible is a part of internal datasets, please contact me by email in profile to share them for reproducing). 
Tracks has no duplicated entries and all shapes are sequential by frame id
2. Wait for "Error: Request failed with status code 500. "AssertionError\n".." message

### Expected Behaviour
Annotations uploaded with no errors

### Your Environment

- Git hash commit: 3e1ccc8602766ec42659360b938781728239ad0e
- Docker version: 20.10.21
- Are you using Docker Swarm or Kubernetes?
- Operating System and version: Ubuntu 20.04  (MacOS 13.1 in case of dev environment)
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
issue introduced by 279f01b53bb50bd7ac64e32ed09705f96e224d34
Not reproducible on previous commit dde9f610df5e57ead2208b62a7799a2cecaa4bfa (if to remove checks for zip archive in cvat-core/src/annotations.ts)
cvat_worker_default log: 
```python
Traceback (most recent call last):
  File "/Users/mikhailtreskin/repos/ml2providence/thirdparty/cvat/.env/lib/python3.9/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/Users/mikhailtreskin/repos/ml2providence/thirdparty/cvat/.env/lib/python3.9/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/Users/mikhailtreskin/repos/ml2providence/thirdparty/cvat/.env/lib/python3.9/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/Users/mikhailtreskin/.pyenv/versions/3.9.0/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/mikhailtreskin/repos/ml2providence/thirdparty/cvat/cvat/apps/dataset_manager/task.py", line 784, in import_task_annotations
    task.import_annotations(f, importer, conv_mask_to_poly=conv_mask_to_poly)
  File "/Users/mikhailtreskin/repos/ml2providence/thirdparty/cvat/cvat/apps/dataset_manager/task.py", line 669, in import_annotations
    self.create(task_data.data.serialize())
  File "/Users/mikhailtreskin/repos/ml2providence/thirdparty/cvat/cvat/apps/dataset_manager/task.py", line 626, in create
    self._patch_data(data, PatchAction.CREATE)
  File "/Users/mikhailtreskin/repos/ml2providence/thirdparty/cvat/cvat/apps/dataset_manager/task.py", line 616, in _patch_data
    self._merge_data(_data, jobs[jid]["start"], self.db_task.overlap)
  File "/Users/mikhailtreskin/repos/ml2providence/thirdparty/cvat/cvat/apps/dataset_manager/task.py", line 620, in _merge_data
    annotation_manager.merge(data, start_frame, overlap)
  File "/Users/mikhailtreskin/repos/ml2providence/thirdparty/cvat/cvat/apps/dataset_manager/annotation.py", line 158, in merge
    tracks.merge(data.tracks, start_frame, overlap)
  File "/Users/mikhailtreskin/repos/ml2providence/thirdparty/cvat/cvat/apps/dataset_manager/annotation.py", line 241, in merge
    cost_matrix[i][j] = 1 - self._calc_objects_similarity(
  File "/Users/mikhailtreskin/repos/ml2providence/thirdparty/cvat/cvat/apps/dataset_manager/annotation.py", line 413, in _calc_objects_similarity
    obj0_shapes = TrackManager.get_interpolated_shapes(obj0, start_frame, end_frame)
  File "/Users/mikhailtreskin/repos/ml2providence/thirdparty/cvat/cvat/apps/dataset_manager/annotation.py", line 751, in get_interpolated_shapes
    assert shape["frame"] > prev_shape["frame"]
AssertionError
```

**Comment by theblenderer** [comment]
Same issue here! Hope it gets resolved soon.

**Comment by yrrah** [comment]
I was able to reproduce this error by uploading COCO formatted labels (no tracks) and running the openvino Person re-ID function on it.

**Comment by PMazarovich** [comment]
We've hit that multiple times.

**Comment by zhiltsov-max** [comment]
Related: https://github.com/cvat-ai/cvat/issues/6779
