### ISSUE TITLE
can not connect to the server

### ISSUE THREAD

**Issue by adreamero** [cvat-ai/cvat#7751]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Context

Hello, our CVAT suddenly has the following error, its version is 2.4.3.
![mmexport1712806589927](https://github.com/cvat-ai/cvat/assets/73162110/33874268-9726-4053-b5af-ac393baab258)

I have given the relevant log information in the environment column, how can I solve this problem ？

### Environment

```Markdown
1、Docker version 24.0.2, build cb74dfc
2、os info：Linux chaoyun2 4.15.0-156-generic #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
3、docker ps log is：
(base) chaoyun@chaoyun2:~/software/cvat-2.4.3$ docker ps | grep cvat
cf402ce4fd75   cvat/ui:v2.4.3                                 "/docker-entrypoint.…"   24 minutes ago   Up 24 minutes                   80/tcp                                                     cvat_ui
5accbc57c3f7   cvat/server:v2.4.3                             "/usr/bin/supervisor…"   24 minutes ago   Up 24 minutes                   8080/tcp                                                   cvat_worker_annotation
939602274a34   cvat/server:v2.4.3                             "/usr/bin/supervisor…"   24 minutes ago   Up 24 minutes                   8080/tcp                                                   cvat_worker_webhooks
3495d8059517   cvat/server:v2.4.3                             "/usr/bin/supervisor…"   24 minutes ago   Up 24 minutes                   8080/tcp                                                   cvat_server
25408eb6a7f8   cvat/server:v2.4.3                             "/usr/bin/supervisor…"   24 minutes ago   Up 24 minutes                   8080/tcp                                                   cvat_utils
fbca2e05f116   cvat/server:v2.4.3                             "/usr/bin/supervisor…"   24 minutes ago   Up 24 minutes                   8080/tcp                                                   cvat_worker_import
e1d43a03d0e3   cvat/server:v2.4.3                             "/usr/bin/supervisor…"   24 minutes ago   Up 24 minutes                   8080/tcp                                                   cvat_worker_export
162eccc81da3   timberio/vector:0.26.0-alpine                  "/usr/local/bin/vect…"   24 minutes ago   Up 24 minutes                                                                              cvat_vector
e631892ff3bd   redis:7.0-alpine                               "docker-entrypoint.s…"   24 minutes ago   Up 24 minutes                   6379/tcp                                                   cvat_redis
786c4049f8ae   postgres:15-alpine                             "docker-entrypoint.s…"   24 minutes ago   Restarting (1) 8 seconds ago                                                               cvat_db
326b43691574   clickhouse/clickhouse-server:22.3-alpine       "/entrypoint.sh"         24 minutes ago   Up 24 minutes                   8123/tcp, 9000/tcp, 9009/tcp                               cvat_clickhouse
921ecdca7163   openpolicyagent/opa:0.45.0-rootless            "/opa run --server -…"   24 minutes ago   Up 24 minutes                                                                              cvat_opa
b8a2d2f8d3b9   cvat.pth.facebookresearch.sam.vit_h:latest     "processor"              6 months ago     Up 6 days (healthy)             0.0.0.0:32768->8080/tcp                                    nuclio-nuclio-pth.facebookresearch.sam.vit_h

4、when i run “docker exec -t cvat_server python manage.py health_check”，the corresponding log is：
(base) chaoyun@chaoyun2:~/software/cvat-2.4.3$ docker exec -t cvat_server python manage.py health_check
ERROR:health-check:unavailable: Database error
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "cvat_db" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/db/backends.py", line 12, in check_status
    obj = TestModel.objects.create(title="test")
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1414, in execute_sql
    with self.connection.cursor() as cursor:
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection
    with self.wrap_database_errors:
  File "/opt/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "cvat_db" to address: Temporary failure in name resolution


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/opt/venv/lib/python3.10/site-packages/health_check/db/backends.py", line 19, in check_status
    raise ServiceUnavailable("Database error")
health_check.exceptions.ServiceUnavailable: unavailable: Database error
ERROR:health-check:unknown error: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles
Traceback (most recent call last):
  File "/home/django/cvat/apps/health/backends.py", line 25, in check_status
    response.raise_for_status()
  File "/opt/venv/lib/python3.10/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/backends.py", line 30, in run_check
    self.check_status()
  File "/home/django/cvat/apps/health/backends.py", line 27, in check_status
    raise HealthCheckException(str(e))
health_check.exceptions.HealthCheckException: unknown error: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles
ERROR:health-check:unavailable: Database is not ready
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "cvat_db" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/health_check/contrib/migrations/backends.py", line 20, in check_status
    executor = MigrationExecutor(connections[db_alias])
  File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/loader.py", line 220, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/opt/venv/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection
    with self.wrap_database_errors:
  File "/opt/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.10/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "cvat_db" to address: Temporary failure in name resolution

Cache backend: default   ... working
Cache backend: media     ... working
DatabaseBackend          ... unavailable: Database error
DiskUsage                ... working
MemoryUsage              ... working
MigrationsHealthCheck    ... unavailable: Database is not ready
OPAHealthCheck           ... unknown error: 500 Server Error: Internal Server Error for url: http://opa:8181/health?bundles
5、the log of “docker logs cvat_db is：
PostgreSQL Database directory appears to contain a database; Skipping initialization

2024-04-11 03:51:49.407 UTC [1] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
2024-04-11 03:51:49.407 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-04-11 03:51:49.407 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-04-11 03:51:49.409 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-04-11 03:51:49.413 UTC [23] LOG:  database system shutdown was interrupted; last known up at 2024-04-11 03:50:46 UTC
2024-04-11 03:51:49.428 UTC [23] LOG:  database system was not properly shut down; automatic recovery in progress
2024-04-11 03:51:49.429 UTC [23] LOG:  redo starts at 0/1920F68
2024-04-11 03:51:49.571 UTC [23] LOG:  invalid record length at 0/1D934F8: wanted 24, got 0
2024-04-11 03:51:49.571 UTC [23] LOG:  redo done at 0/1D934C0 system usage: CPU: user: 0.04 s, system: 0.08 s, elapsed: 0.14 s
2024-04-11 03:51:49.583 UTC [21] LOG:  checkpoint starting: end-of-recovery immediate wait
2024-04-11 03:51:49.631 UTC [21] LOG:  request to flush past end of generated WAL; request 0/1E98EF0, current position 0/1D934F8
2024-04-11 03:51:49.631 UTC [21] CONTEXT:  writing block 0 of relation base/1/2619_vm
2024-04-11 03:51:49.631 UTC [21] ERROR:  xlog flush request 0/1E98EF0 is not satisfied --- flushed only to 0/1D934F8
2024-04-11 03:51:49.631 UTC [21] CONTEXT:  writing block 0 of relation base/1/2619_vm
2024-04-11 03:51:49.631 UTC [23] FATAL:  checkpoint request failed
2024-04-11 03:51:49.631 UTC [23] HINT:  Consult recent messages in the server log for details.
2024-04-11 03:51:49.636 UTC [1] LOG:  startup process (PID 23) exited with exit code 1
2024-04-11 03:51:49.636 UTC [1] LOG:  terminating any other active server processes
2024-04-11 03:51:49.637 UTC [1] LOG:  shutting down due to startup process failure
2024-04-11 03:51:49.641 UTC [1] LOG:  database system is shut down
```

**Comment by bsekachev** [comment]
Please, try the latest release first. We will not consider issues from strongly outdated versions.

**Comment by tsune10696** [comment]
@bsekachev 
@adreamero 

↑ Has this problem been resolved?
If it has been resolved, I would like to know how it was resolved.
