### ISSUE TITLE
Unable to upload video to a cvat task

### ISSUE THREAD

**Issue by asbjorndanielsen** [cvat-ai/cvat#8177]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Installed CVAT from https://github.com/cvat-ai/cvat/tree/master
2. Adapted CVAT installation to use automated annotations
3. Started CVAT, and tried to upload a video file.
4. Error message when trying to access Project:
TypeError
Cannot read properties of undefined (reading 'message')

TypeError: Cannot read properties of undefined (reading 'message')
    at qTe.componentDidMount (https://annotate.chronos.ai/assets/cvat-ui.73692c5c1a91b0b7ba5c.min.js:2:7594821)
    at Al (https://annotate.chronos.ai/assets/cvat-ui.73692c5c1a91b0b7ba5c.min.js:2:4433803)
    at _l (https://annotate.chronos.ai/assets/cvat-ui.73692c5c1a91b0b7ba5c.min.js:2:4433588)
    at yl (https://annotate.chronos.ai/assets/cvat-ui.73692c5c1a91b0b7ba5c.min.js:2:4433132)
    at https://annotate.chronos.ai/assets/cvat-ui.73692c5c1a91b0b7ba5c.min.js:2:4444789
    at wc (https://annotate.chronos.ai/assets/cvat-ui.73692c5c1a91b0b7ba5c.min.js:2:4445291)
    at cc (https://annotate.chronos.ai/assets/cvat-ui.73692c5c1a91b0b7ba5c.min.js:2:4439107)
    at Ha (https://annotate.chronos.ai/assets/cvat-ui.73692c5c1a91b0b7ba5c.min.js:2:4380083)
    at https://annotate.chronos.ai/assets/cvat-ui.73692c5c1a91b0b7ba5c.min.js:2:4436535
Steps to reproduce the issue
Your operating system and browser version
CVAT version
Server: 2.16.0
Core: 15.1.0
Canvas: 2.20.6
UI: 1.64.0

5. Error Message in Task window:
Could not create the task

tus: failed to resume upload, caused by [object ProgressEvent], originated from request (method: HEAD, url: http://annotate.chronos.ai/api/tasks/15/data/562ad055-81f9-4e16-a939-6a2f8a469b2d, response code: n/a, response text: n/a, request id: n/a). 

### Expected Behavior

Loading imagers into CVAT works, however uploading the video into CVAT does not

### Environment

```Markdown
Docker version 27.0.3
Ubuntu 22.04 LTS
Nvidia Driver 535.183.01
```

**Comment by bsekachev** [comment]
Please, refer to #8153

There is a similar problem, `http` is used to upload video when CVAT deployed on https.
