### ISSUE TITLE
Unable to upload images with the same file name

### ISSUE THREAD

**Issue by jackylamhk** [cvat-ai/cvat#8201]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Upload remote data via Task > Create > Select files > Remote sources
2. Upload the same file again in another task

### Expected Behavior

The task creates successfully with the same file

### Possible Solution

1. Re-use the same remote data for the task
2. Catch the error and return a specific error code with the reason, for example, "Remote data "{file_name}" already exists," instead of letting Django return a 500

### Context

Logs captured from stdout:
```
{server_ip} - - [19/Jul/2024:17:15:02 +0000] "POST /api/tasks/{task_id}/data?org={org_slug} HTTP/1.1" 202 0 "https://{server_hostname}/tasks/create" "{user_agent}"

2024-07-19 17:15:03,374 DEBG 'uvicorn-0' stderr output:
[2024-07-19 17:15:03,374] ERROR django.request: Internal Server Error: /api/tasks/{task_id}/data
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "engine_remotefile_data_id_file_{constraint_id}_uniq"
DETAIL:  Key (data_id, file)=({data_id}, https://{remote_image_url}.jpg) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/django/cvat/apps/engine/views.py", line 1217, in data
    return self.upload_data(request)
  File "/home/django/cvat/apps/engine/mixins.py", line 229, in upload_data
    return self.upload_finished(request)
  File "/home/django/cvat/apps/engine/views.py", line 1099, in upload_finished
    return _handle_upload_data(request)
  File "/home/django/cvat/apps/engine/views.py", line 1033, in _handle_upload_data
    db_data = serializer.save()
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/home/django/cvat/apps/engine/serializers.py", line 1036, in update
    self._create_files(instance, files)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/serializers.py", line 1065, in _create_files
    files_model.objects.bulk_create(
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 803, in bulk_create
    returned_columns = self._batched_insert(
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1831, in _batched_insert
    self._insert(
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "engine_remotefile_data_id_file_{constraint_id}_uniq"
DETAIL:  Key (data_id, file)=({data_id}, https://{remote_image_url}.jpg) already exists.


2024-07-19 17:15:03,384 DEBG 'uvicorn-0' stdout output:
INFO:     {user_ip}:0 - "POST /api/tasks/{task_id}/data?org={org_slug} HTTP/1.0" 500 Internal Server Error
```

### Environment

```Markdown
v2.12.0
```

**Comment by bsekachev** [comment]
Dublicate https://github.com/cvat-ai/cvat/issues/1250
