### ISSUE TITLE
how to fix this problem

### ISSUE THREAD

**Issue by s0966066980** [cvat-ai/cvat#8239]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

TypeError
o.map is not a function

TypeError: o.map is not a function
    at NB (http://localhost:8080/assets/cvat-ui.36cd03e8092dcb596625.min.js:2:8684205)
    at Ei (http://localhost:8080/assets/cvat-ui.36cd03e8092dcb596625.min.js:2:4397481)
    at Oa (http://localhost:8080/assets/cvat-ui.36cd03e8092dcb596625.min.js:2:4409062)
    at Ea (http://localhost:8080/assets/cvat-ui.36cd03e8092dcb596625.min.js:2:4408276)
    at Ca (http://localhost:8080/assets/cvat-ui.36cd03e8092dcb596625.min.js:2:4407890)
    at Es (http://localhost:8080/assets/cvat-ui.36cd03e8092dcb596625.min.js:2:4457289)
    at _c (http://localhost:8080/assets/cvat-ui.36cd03e8092dcb596625.min.js:2:4443217)
    at bc (http://localhost:8080/assets/cvat-ui.36cd03e8092dcb596625.min.js:2:4443145)
    at vc (http://localhost:8080/assets/cvat-ui.36cd03e8092dcb596625.min.js:2:4443008)
    at ic (http://localhost:8080/assets/cvat-ui.36cd03e8092dcb596625.min.js:2:4439843)

**Comment by bsekachev** [comment]
Please, provide correct steps to reproduce, screencast if possible and fill the environment section. We do not know what version you are using.

**Comment by s0966066980** [comment]
Using v2.16.1, currently docker can operate normally, but is stuck on the login screen.
![2024-07-31 14-44-59 的螢幕擷圖](https://github.com/user-attachments/assets/7d8eb6b0-6242-4377-985b-03ddd500e697)

**Comment by bsekachev** [comment]
We can't investigate the problem on your side. 

I may recommend you to look at:

`docker ps` to see a list of services and their state. Be sure everything is running and healthy. 
`docker logs <container_name>` to see logs from specific container. I would recommend to check logs from `cvat_server` container first of all.
