### ISSUE TITLE
Engine Job Commit Table Not Being Created

### ISSUE THREAD

**Issue by Shadowfear36** [cvat-ai/cvat#8472]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Use an existing CVAT external Postgres Database
Enter the cvat_server bash and attempt:
`python manage.py makemigrations`
` python manage.py migrate`
Show Migrations will explain that their is no pending migrations.

But this migration task in the engine does not complete for some reason
 [x] 0018_jobcommit
 
 

### Expected Behavior

To be able to save new annotations on CVAT dataset.

### Possible Solution

Do not have suggestion quite yet.

### Context

This migration does not seem to be applying to my database:
 [x] 0018_jobcommit
 
 
 ```
 cvat_server             | [Wed Sep 25 21:34:34.778353 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568] ERROR:django.request:Internal Server Error: /api/jobs/320/annotations
cvat_server             | [Wed Sep 25 21:34:34.778359 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568] Traceback (most recent call last):
cvat_server             | [Wed Sep 25 21:34:34.778362 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
cvat_server             | [Wed Sep 25 21:34:34.778365 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     return self.cursor.execute(sql, params)
cvat_server             | [Wed Sep 25 21:34:34.778368 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568] psycopg2.errors.UndefinedTable: relation "engine_jobcommit" does not exist
cvat_server             | [Wed Sep 25 21:34:34.778371 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568] LINE 1: INSERT INTO "engine_jobcommit" ("scope", "owner_id", "timest...
cvat_server             | [Wed Sep 25 21:34:34.778374 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]                     ^
cvat_server             | [Wed Sep 25 21:34:34.778377 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568] 
cvat_server             | [Wed Sep 25 21:34:34.778379 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568] 
cvat_server             | [Wed Sep 25 21:34:34.778381 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568] The above exception was the direct cause of the following exception:
cvat_server             | [Wed Sep 25 21:34:34.778384 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568] 
cvat_server             | [Wed Sep 25 21:34:34.778386 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568] Traceback (most recent call last):
cvat_server             | [Wed Sep 25 21:34:34.778389 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
cvat_server             | [Wed Sep 25 21:34:34.778392 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     response = get_response(request)
cvat_server             | [Wed Sep 25 21:34:34.778395 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
cvat_server             | [Wed Sep 25 21:34:34.778398 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
cvat_server             | [Wed Sep 25 21:34:34.778401 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
cvat_server             | [Wed Sep 25 21:34:34.778403 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     return view_func(*args, **kwargs)
cvat_server             | [Wed Sep 25 21:34:34.778406 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
cvat_server             | [Wed Sep 25 21:34:34.778409 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     return self.dispatch(request, *args, **kwargs)
cvat_server             | [Wed Sep 25 21:34:34.778412 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
cvat_server             | [Wed Sep 25 21:34:34.778415 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     response = self.handle_exception(exc)
cvat_server             | [Wed Sep 25 21:34:34.778418 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
cvat_server             | [Wed Sep 25 21:34:34.778420 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     self.raise_uncaught_exception(exc)
cvat_server             | [Wed Sep 25 21:34:34.778423 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
cvat_server             | [Wed Sep 25 21:34:34.778426 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     raise exc
cvat_server             | [Wed Sep 25 21:34:34.778430 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
cvat_server             | [Wed Sep 25 21:34:34.778433 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     response = handler(request, *args, **kwargs)
cvat_server             | [Wed Sep 25 21:34:34.778436 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/home/django/cvat/apps/engine/views.py", line 1547, in annotations
cvat_server             | [Wed Sep 25 21:34:34.778439 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     data = dm.task.patch_job_data(pk, serializer.data, action)
cvat_server             | [Wed Sep 25 21:34:34.778442 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/home/django/cvat/apps/profiler.py", line 11, in wrapped
cvat_server             | [Wed Sep 25 21:34:34.778444 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     return f(*args, **kwargs)
cvat_server             | [Wed Sep 25 21:34:34.778447 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/home/django/cvat/apps/engine/plugins.py", line 56, in function_wrapper
cvat_server             | [Wed Sep 25 21:34:34.778450 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     result = function_to_decorate(*args, **kwargs)
cvat_server             | [Wed Sep 25 21:34:34.778453 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
cvat_server             | [Wed Sep 25 21:34:34.778455 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     return func(*args, **kwds)
cvat_server             | [Wed Sep 25 21:34:34.778458 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/home/django/cvat/apps/dataset_manager/task.py", line 698, in patch_job_data
cvat_server             | [Wed Sep 25 21:34:34.778461 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     annotation.create(data)
cvat_server             | [Wed Sep 25 21:34:34.778463 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/home/django/cvat/apps/dataset_manager/task.py", line 316, in create
cvat_server             | [Wed Sep 25 21:34:34.778466 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     self._create(data)
cvat_server             | [Wed Sep 25 21:34:34.778469 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/home/django/cvat/apps/dataset_manager/task.py", line 313, in _create
cvat_server             | [Wed Sep 25 21:34:34.778472 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     self.db_job.save()
cvat_server             | [Wed Sep 25 21:34:34.778474 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/home/django/cvat/apps/engine/models.py", line 502, in save
cvat_server             | [Wed Sep 25 21:34:34.778477 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     db_commit.save()
cvat_server             | [Wed Sep 25 21:34:34.778480 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
cvat_server             | [Wed Sep 25 21:34:34.778482 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     self.save_base(using=using, force_insert=force_insert,
cvat_server             | [Wed Sep 25 21:34:34.778485 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
cvat_server             | [Wed Sep 25 21:34:34.778489 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     updated = self._save_table(
cvat_server             | [Wed Sep 25 21:34:34.778493 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
cvat_server             | [Wed Sep 25 21:34:34.778498 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
cvat_server             | [Wed Sep 25 21:34:34.778502 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
cvat_server             | [Wed Sep 25 21:34:34.778508 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     return manager._insert(
cvat_server             | [Wed Sep 25 21:34:34.778512 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
cvat_server             | [Wed Sep 25 21:34:34.778517 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     return getattr(self.get_queryset(), name)(*args, **kwargs)
cvat_server             | [Wed Sep 25 21:34:34.778521 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
cvat_server             | [Wed Sep 25 21:34:34.778526 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     return query.get_compiler(using=using).execute_sql(returning_fields)
cvat_server             | [Wed Sep 25 21:34:34.778529 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
cvat_server             | [Wed Sep 25 21:34:34.778532 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     cursor.execute(sql, params)
cvat_server             | [Wed Sep 25 21:34:34.778535 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
cvat_server             | [Wed Sep 25 21:34:34.778538 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
cvat_server             | [Wed Sep 25 21:34:34.778540 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
cvat_server             | [Wed Sep 25 21:34:34.778543 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     return executor(sql, params, many, context)
cvat_server             | [Wed Sep 25 21:34:34.778546 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
cvat_server             | [Wed Sep 25 21:34:34.778549 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     return self.cursor.execute(sql, params)
cvat_server             | [Wed Sep 25 21:34:34.778552 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
cvat_server             | [Wed Sep 25 21:34:34.778555 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     raise dj_exc_value.with_traceback(traceback) from exc_value
cvat_server             | [Wed Sep 25 21:34:34.778558 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
cvat_server             | [Wed Sep 25 21:34:34.778560 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     return self.cursor.execute(sql, params)
cvat_server             | [Wed Sep 25 21:34:34.778563 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568] django.db.utils.ProgrammingError: relation "engine_jobcommit" does not exist
cvat_server             | [Wed Sep 25 21:34:34.778566 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568] LINE 1: INSERT INTO "engine_jobcommit" ("scope", "owner_id", "timest...
cvat_server             | [Wed Sep 25 21:34:34.778569 2024] [wsgi:error] [pid 319:tid 139734860437248] [remote 172.19.0.2:34568]     
```

As you can see when attempting to save a new annotation to an image. I get this server error.
Any attempt to manually migrate does not change the result. 

```
ocker exec -it cvat_server bash
WARNING: Error loading config file: open /home/rd/.docker/config.json: permission denied
django@78a0ea8033b0:~$ python manage.py showmigrations
account
 [X] 0001_initial
 [X] 0002_email_max_length
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
 [X] 0003_logentry_add_action_flag_choices
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
 [X] 0010_alter_group_name_max_length
 [X] 0011_update_proxy_permissions
 [X] 0012_alter_user_first_name_max_length
authtoken
 [X] 0001_initial
 [X] 0002_auto_20160226_1747
 [X] 0003_tokenproxy
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
dataset_repo
 [X] 0001_initial (1 squashed migrations)
 [X] 0002_auto_20190123_1305 (1 squashed migrations)
 [X] 0003_gitdata_lfs (1 squashed migrations)
 [X] 0004_rename
 [X] 0005_auto_20201019_1100
 [X] 0006_gitdata_format
db
 [X] 0001_initial (1 squashed migrations)
engine
 [X] 0001_release_v0_1_0
 [X] 0002_labeledpoints_labeledpointsattributeval_labeledpolygon_labeledpolygonattributeval_labeledpolyline_la
 [X] 0003_objectpath_shapes
 [X] 0004_task_z_order
 [X] 0005_auto_20180609_1512
 [X] 0006_auto_20180629_1501
 [X] 0007_task_flipped
 [X] 0008_auto_20180917_1424
 [X] 0009_auto_20180917_1424
 [X] 0010_auto_20181011_1517
 [X] 0011_add_task_source_and_safecharfield
 [X] 0012_auto_20181025_1618
 [X] 0013_auth_no_default_permissions
 [X] 0014_job_max_shape_id
 [X] 0015_db_redesign_20190217
 [X] 0016_attribute_spec_20190217
 [X] 0017_db_redesign_20190221
 [X] 0018_jobcommit
 [X] 0019_frame_selection
 [X] 0020_remove_task_flipped
 [X] 0021_auto_20190826_1827
 [X] 0022_auto_20191004_0817
 [X] 0023_auto_20200113_1323
 [X] 0024_auto_20191023_1025
 [X] 0025_auto_20200324_1222
 [X] 0026_auto_20200719_1511
 [X] 0027_auto_20200719_1552
 [X] 0028_labelcolor
 [X] 0029_data_storage_method
 [X] 0030_auto_20200914_1331
 [X] 0031_auto_20201011_0220
 [X] 0032_remove_task_z_order
 [X] 0033_projects_adjastment
 [X] 0034_auto_20201125_1426
 [X] 0035_data_storage
 [X] 0036_auto_20201216_0943
 [X] 0037_task_subset
 [X] 0038_manifest
 [X] 0039_auto_training
 [X] 0040_cloud_storage
 [X] 0041_auto_20210827_0258
 [X] 0042_auto_20210830_1056
 [X] 0043_auto_20211027_0718
 [X] 0044_auto_20211115_0858
 [X] 0045_auto_20211123_0824 (1 squashed migrations)
 [X] 0046_data_sorting_method (1 squashed migrations)
 [X] 0047_auto_20211110_1938
 [X] 0048_auto_20211112_1918
 [X] 0049_auto_20220202_0710
 [X] 0050_auto_20220211_1425
 [X] 0051_auto_20220220_1824
 [X] 0052_alter_cloudstorage_specific_attributes
 [X] 0053_data_deleted_frames
 [X] 0054_auto_20220610_1829
 [X] 0055_jobs_directories
 [X] 0056_jobs_previews
 [X] 0057_auto_20220726_0926
 [X] 0058_auto_20220809_1236
 [X] 0059_labeledshape_outside
 [X] 0060_alter_label_parent
 [X] 0061_auto_20221130_0844
opencv
 (no migrations)
organizations
 [X] 0001_initial
sessions
 [X] 0001_initial
sites
 [X] 0001_initial
 [X] 0002_alter_domain_unique
socialaccount
 [X] 0001_initial
 [X] 0002_token_max_lengths
 [X] 0003_extra_data_default_dict
webhooks
 [X] 0001_initial
 [X] 0002_alter_webhookdelivery_status_code
 [X] 0003_alter_webhookdelivery_status_code
 ```
 ```
  python manage.py makemigrations engine
No changes detected in app 'engine'
```
 
 ```
 python manage.py migrate engine
Operations to perform:
  Apply all migrations: engine
Running migrations:
  No migrations to apply.
  ```
  
  External database so no cvat_db to log. I can dump it and apply it to a docker postgres instance to see what logs spit out, if need be. 

### Environment

```Markdown
Linux
Postgres
CVAT-2.3
External CVAT Postgres Database
```

**Comment by Shadowfear36** [comment]
```
 public | engine_annotationguide             | table | postgres
 public | engine_asset                       | table | postgres
 public | engine_attributespec               | table | postgres
 public | engine_clientfile                  | table | postgres
 public | engine_cloudstorage                | table | postgres
 public | engine_comment                     | table | postgres
 public | engine_data                        | table | postgres
 public | engine_image                       | table | postgres
 public | engine_issue                       | table | postgres
 public | engine_job                         | table | postgres
 public | engine_label                       | table | postgres
 public | engine_labeledimage                | table | postgres
 public | engine_labeledimageattributeval    | table | postgres
 public | engine_labeledshape                | table | postgres
 public | engine_labeledshapeattributeval    | table | postgres
 public | engine_labeledtrack                | table | postgres
 public | engine_labeledtrackattributeval    | table | postgres
 public | engine_manifest                    | table | postgres
 public | engine_profile                     | table | postgres
 public | engine_project                     | table | postgres
 public | engine_relatedfile                 | table | postgres
 public | engine_remotefile                  | table | postgres
 public | engine_segment                     | table | postgres
 public | engine_serverfile                  | table | postgres
 public | engine_skeleton                    | table | postgres
 public | engine_storage                     | table | postgres
 public | engine_task                        | table | postgres
 public | engine_trackedshape                | table | postgres
 public | engine_trackedshapeattributeval    | table | postgres
 public | engine_video                       | table | postgres
 ```
 
 All the tables within the database that start with engine

**Comment by Shadowfear36** [comment]
> @Shadowfear36
> 
> 1. What is the reason for running migrations manually?
> 2. Version 2.3 is too old, please use the current version
> 3. Your CVAT code and database scheme do not match, most likely you deployed a newer version first which removes jobcommit and then migrated to version 2.3 https://github.com/cvat-ai/cvat/blob/develop/cvat/apps/engine/migrations/0063_delete_jobcommit.py
> 
> I'm closing the issue for now, please use the actual version and provide the exact steps to reproduce it

Oh wow, I didnt realize that 2.3 was so outdated. This all makes so much sense. I did a fresh clone of the repo and everything booted perfectly up. Thank you. The reason I thought 2.3 was the answer was because an error I had recieved from a previous version sent me to the 1.7 to 2.3 upgrade guide.
Thank you for pointing out my obliviousness.
