### ISSUE TITLE
cvat_sdk producing UnauthorizedException: Status Code: 401 upon `job.export_dataset` call

### ISSUE THREAD

**Issue by fortminors** [cvat-ai/cvat#8660]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Launch the minimal reproducing script:
```python
from cvat_sdk import make_client

EXPORT_FORMAT = "CVAT for images 1.1"
SERVER_URL = "SERVER_URL"
CREDENTIALS = ("username", "password")
ORGANIZATION = "TEST_ORG"

if __name__ == "__main__":
    with make_client(SERVER_URL, credentials=CREDENTIALS) as client:
        client.organization_slug = ORGANIZATION
        jobs = client.jobs.list()
        assert len(jobs) > 0, "No jobs found"
        jobs[0].export_dataset(EXPORT_FORMAT, "test_job.zip", include_images=True)
```

### Expected Behavior

I expected the job dataset to be downloaded in `CVAT for images 1.1` format and saved to `test_job.zip` file. I am using the same script as I've implemented a while ago with previous versions of server and cvat_sdk. It worked well before, but after upgrading to the latest versions, it started showing this error and I am unable to export datasets

### Possible Solution

Perhaps, allow authorization with a token and add the possibility for token creation in the UI.

### Context

I am getting the following traceback

```python
Traceback (most recent call last):
  File "/dir/script.py", line 38, in <module>
    jobs[0].export_dataset(EXPORT_FORMAT, "test_job.zip", include_images=True)
  File "/dir/.venv/lib/python3.11/site-packages/cvat_sdk/core/proxies/model_proxy.py", line 326, in export_dataset
    self.export(
  File "/dir/.venv/lib/python3.11/site-packages/cvat_sdk/core/proxies/model_proxy.py", line 291, in export
    downloader.download_file(result_url, output_path=Path(filename), pbar=pbar)
  File "/dir/.venv/lib/python3.11/site-packages/cvat_sdk/core/downloading.py", line 49, in download_file
    response = self._client.api_client.rest_client.GET(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dir/.venv/lib/python3.11/site-packages/cvat_sdk/api_client/rest.py", line 217, in GET
    return self.request("GET", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dir/.venv/lib/python3.11/site-packages/cvat_sdk/api_client/rest.py", line 200, in request
    raise UnauthorizedException(http_resp=r)
cvat_sdk.api_client.exceptions.UnauthorizedException: Status Code: 401
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Thu, 07 Nov 2024 14:00:28 GMT', 'Content-Type': 'application/vnd.cvat+json', 'Content-Length': '58', 'Connection': 'keep-alive', 'Allow': 'GET, HEAD, OPTIONS', 'Cross-Origin-Opener-Policy': 'same-origin', 'Referrer-Policy': 'same-origin, strict-origin-when-cross-origin', 'Vary': 'Accept, Origin, Cookie', 'Www-Authenticate': 'Token', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-Frame-Options': 'DENY', 'X-Request-Id': 'adaae706-abe4-7235-b6c7-59179mbd0263'})
HTTP response body: b'{"detail":"Authentication credentials were not provided."}'
```

### Environment

```Markdown
- Ubuntu 22.04
- 6.8.0-48-generic
- cvat_sdk==2.21.3
- self-hosted CVAT instance
```

**Comment by fortminors** [comment]
Interestingly, I've found out I can't even download anything in the UI, I get the following error in the developer console in browser:
`Failed to load resource: the server responded with a status of 404 ()`

**Comment by zhiltsov-max** [comment]
Hi, the issue should be resolved in https://github.com/cvat-ai/cvat/pull/9568
