### ISSUE TITLE
I can't create a task in a project

### ISSUE THREAD

**Issue by azadehashouri** [cvat-ai/cvat#8695]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Context

Hi 
I can not create a new task in a project.

Could you help me?

I doesn't matter I use superuser or not, it isn't working and I get this error every time:

![image](https://github.com/user-attachments/assets/a3d492f3-0c63-4394-981b-05b05e33cbf2)

**Comment by bsekachev** [comment]
`docker logs cvat_server`?

**Comment by MostlyKIGuess** [comment]
Can you give steps to reproduce?

**Comment by azadehashouri** [comment]
> Can you give steps to reproduce?

I wanted to do this, but when I created superuser, I came across this error that the django super user is created before with this username and when I logged into CVAT using my browser the project of my previous CVAT was still there, as I deleted all previous CVAT images and related containers.

@MostlyKIGuess

**Comment by azadehashouri** [comment]
> `docker logs cvat_server`?

@bsekachev Here you are

```
$ sudo docker logs cvat_server
wait-for-it.sh: waiting for cvat_db:5432 without a timeout
wait-for-it.sh: cvat_db:5432 is available after 0 seconds
Operations to perform:
  Apply all migrations: account, admin, analytics_report, auth, authtoken, contenttypes, dataset_repo, db, django_rq, engine, organizations, quality_control, sessions, sites, socialaccount, webhooks
Running migrations:
  No migrations to apply.

163 static files copied to '/home/django/static'.
wait-for-it.sh: waiting for cvat_db:5432 without a timeout
wait-for-it.sh: cvat_db:5432 is available after 0 seconds
waiting for migrations to complete...
2024-11-16 04:50:01,063 INFO Creating socket unix:///tmp/uvicorn.sock
2024-11-16 04:50:01,064 INFO Closing socket unix:///tmp/uvicorn.sock
2024-11-16 04:50:01,067 INFO RPC interface 'supervisor' initialized
2024-11-16 04:50:01,067 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-11-16 04:50:01,067 INFO supervisord started with pid 1
2024-11-16 04:50:02,072 INFO spawned: 'clamav_update' with pid 74
2024-11-16 04:50:02,075 INFO spawned: 'nginx-0' with pid 75
2024-11-16 04:50:02,079 INFO spawned: 'smokescreen' with pid 76
2024-11-16 04:50:02,080 INFO Creating socket unix:///tmp/uvicorn.sock
2024-11-16 04:50:02,082 DEBG fd 20 closed, stopped monitoring <PInputDispatcher at 140287265682768 for <Subprocess at 140287265671392 with name uvicorn-0 in state STARTING> (stdin)>
2024-11-16 04:50:02,084 INFO spawned: 'uvicorn-0' with pid 77
2024-11-16 04:50:02,086 DEBG fd 24 closed, stopped monitoring <PInputDispatcher at 140287265683344 for <Subprocess at 140287265671248 with name uvicorn-1 in state STARTING> (stdin)>
2024-11-16 04:50:02,088 INFO spawned: 'uvicorn-1' with pid 78
2024-11-16 04:50:02,089 DEBG fd 7 closed, stopped monitoring <POutputDispatcher at 140287265223344 for <Subprocess at 140287265223248 with name clamav_update in state STARTING> (stdout)>
2024-11-16 04:50:02,089 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 140287265681184 for <Subprocess at 140287265223248 with name clamav_update in state STARTING> (stderr)>
2024-11-16 04:50:02,089 INFO exited: clamav_update (exit status 0; expected)
2024-11-16 04:50:02,090 DEBG received SIGCHLD indicating a child quit
2024-11-16 04:50:02,093 DEBG 'smokescreen' stderr output:
{"level":"info","msg":"starting","time":"2024-11-16T04:50:02Z"}

2024-11-16 04:50:02,101 DEBG 'uvicorn-0' stderr output:
wait-for-it.sh: waiting for cvat_db:5432 without a timeout

2024-11-16 04:50:02,109 DEBG 'uvicorn-0' stderr output:
wait-for-it.sh: cvat_db:5432 is available after 0 seconds

2024-11-16 04:50:02,110 DEBG 'uvicorn-1' stderr output:
wait-for-it.sh: waiting for cvat_db:5432 without a timeout

2024-11-16 04:50:02,116 DEBG 'uvicorn-1' stderr output:
wait-for-it.sh: cvat_db:5432 is available after 0 seconds

2024-11-16 04:50:02,122 DEBG 'uvicorn-0' stderr output:
wait-for-it.sh: waiting for cvat_redis_inmem:6379 without a timeout

2024-11-16 04:50:02,127 DEBG 'uvicorn-1' stderr output:
wait-for-it.sh: waiting for cvat_redis_inmem:6379 without a timeout

2024-11-16 04:50:02,128 DEBG 'uvicorn-0' stderr output:
wait-for-it.sh: cvat_redis_inmem:6379 is available after 0 seconds

2024-11-16 04:50:02,134 DEBG 'uvicorn-1' stderr output:
wait-for-it.sh: cvat_redis_inmem:6379 is available after 0 seconds

2024-11-16 04:50:02,140 DEBG 'uvicorn-0' stderr output:
wait-for-it.sh: waiting for cvat_redis_ondisk:6666 without a timeout

2024-11-16 04:50:02,145 DEBG 'uvicorn-1' stderr output:
wait-for-it.sh: waiting for cvat_redis_ondisk:6666 without a timeout

2024-11-16 04:50:02,146 DEBG 'uvicorn-0' stderr output:
wait-for-it.sh: cvat_redis_ondisk:6666 is available after 0 seconds

2024-11-16 04:50:02,152 DEBG 'uvicorn-1' stderr output:
wait-for-it.sh: cvat_redis_ondisk:6666 is available after 0 seconds

2024-11-16 04:50:02,183 DEBG 'nginx-0' stderr output:
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)

2024-11-16 04:50:02,554 DEBG fd 14 closed, stopped monitoring <POutputDispatcher at 140287265681424 for <Subprocess at 140287265670672 with name nginx-0 in state STARTING> (stderr)>
2024-11-16 04:50:03,556 INFO success: nginx-0 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-11-16 04:50:03,556 INFO success: smokescreen entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-11-16 04:50:03,557 INFO success: uvicorn-0 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-11-16 04:50:03,557 INFO success: uvicorn-1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-11-16 04:50:04,798 DEBG 'uvicorn-0' stderr output:
INFO:     Started server process [77]
INFO:     Waiting for application startup.

2024-11-16 04:50:04,799 DEBG 'uvicorn-0' stderr output:
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.

2024-11-16 04:50:04,800 DEBG 'uvicorn-0' stderr output:
INFO:     Uvicorn running on socket /tmp/uvicorn.sock (Press CTRL+C to quit)

2024-11-16 04:50:04,850 DEBG 'uvicorn-1' stderr output:
INFO:     Started server process [78]
INFO:     Waiting for application startup.

2024-11-16 04:50:04,850 DEBG 'uvicorn-1' stderr output:
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.

2024-11-16 04:50:04,850 DEBG 'uvicorn-1' stderr output:
INFO:     Uvicorn running on socket /tmp/uvicorn.sock (Press CTRL+C to quit)

2024-11-16 04:50:05,669 DEBG 'uvicorn-0' stdout output:
INFO:     172.30.227.7:0 - "POST /api/auth/login?org= HTTP/1.0" 200 OK

2024-11-16 04:50:05,690 DEBG 'uvicorn-0' stdout output:
INFO:     172.21.0.2:0 - "GET /api/auth/rules HTTP/1.0" 200 OK

2024-11-16 04:50:06,110 DEBG 'uvicorn-1' stdout output:
INFO:     172.30.227.7:0 - "GET /api/users/self?org= HTTP/1.0" 200 OK

2024-11-16 04:50:06,177 DEBG 'uvicorn-1' stdout output:
INFO:     172.30.227.7:0 - "GET /api/server/about?org= HTTP/1.0" 200 OK

2024-11-16 04:50:06,195 DEBG 'uvicorn-0' stdout output:
INFO:     172.30.227.7:0 - "GET /api/server/annotation/formats?org= HTTP/1.0" 200 OK

2024-11-16 04:50:06,225 DEBG 'uvicorn-1' stdout output:
INFO:     172.30.227.7:0 - "GET /api/invitations?page=1&filter=%7B%22and%22:[%7B%22%3D%3D%22:[%7B%22var%22:%22user_id%22%7D,%222%22]%7D,+%7B%22%3D%3D%22:[%7B%22var%22:%22accepted%22%7D,false]%7D]%7D&page_size=11 HTTP/1.0" 200 OK

2024-11-16 04:50:06,227 DEBG 'uvicorn-1' stdout output:
INFO:     172.30.227.7:0 - "GET /api/organizations?org=&filter=%7B%22and%22:[%7B%22%3D%3D%22:[%7B%22var%22:%22slug%22%7D,%22Farashenasa%22]%7D]%7D HTTP/1.0" 200 OK

2024-11-16 04:50:06,501 DEBG 'uvicorn-0' stdout output:
INFO:     172.30.227.7:0 - "GET /api/requests?org=Farashenasa&page_size=500&page=1 HTTP/1.0" 200 OK

2024-11-16 04:50:06,510 DEBG 'uvicorn-1' stdout output:
INFO:     172.30.227.7:0 - "GET /api/organizations?org=Farashenasa HTTP/1.0" 200 OK

2024-11-16 04:50:09,919 DEBG 'uvicorn-1' stdout output:
INFO:     172.30.227.7:0 - "GET /api/projects?org=Farashenasa&names_only=true&page=1&page_size=10&search= HTTP/1.0" 200 OK

2024-11-16 04:50:10,651 DEBG 'uvicorn-1' stdout output:
INFO:     172.30.227.7:0 - "GET /api/projects/11 HTTP/1.0" 200 OK

2024-11-16 04:50:10,766 DEBG 'uvicorn-1' stdout output:
INFO:     172.30.227.7:0 - "GET /api/labels?project_id=11&org=Farashenasa&page_size=500&page=1 HTTP/1.0" 200 OK

2024-11-16 04:50:15,501 DEBG 'uvicorn-1' stdout output:
INFO:     172.30.227.7:0 - "GET /api/projects/11 HTTP/1.0" 200 OK

2024-11-16 04:50:15,583 DEBG 'uvicorn-1' stdout output:
INFO:     172.30.227.7:0 - "GET /api/labels?project_id=11&org=Farashenasa&page_size=500&page=1 HTTP/1.0" 200 OK

2024-11-16 04:50:15,817 DEBG 'uvicorn-0' stderr output:
[2024-11-16 04:50:15,815] ERROR django.request: Internal Server Error: /api/tasks
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
cvat.apps.quality_control.models.QualitySettings.DoesNotExist: QualitySettings matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "point_size_base" of relation "quality_control_qualitysettings" violates not-null constraint
DETAIL:  Failing row contains (25, 0.4, 0.09, 0.01, 0.8, t, 0.1, t, 0.5, t, 0.05, t, t, 25, 0, accuracy, 0.7, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
  File "/opt/venv/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.10/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 193, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/views.py", line 979, in perform_create
    serializer.save(
  File "/opt/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/serializers.py", line 1183, in create
    db_task = models.Task.objects.create(
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/opt/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/opt/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/django/cvat/apps/quality_control/signals.py", line 66, in __save_task__initialize_quality_settings
    QualitySettings.objects.get_or_create(task=task)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 923, in get_or_create
    return self.create(**params), True
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "point_size_base" of relation "quality_control_qualitysettings" violates not-null constraint
DETAIL:  Failing row contains (25, 0.4, 0.09, 0.01, 0.8, t, 0.1, t, 0.5, t, 0.05, t, t, 25, 0, accuracy, 0.7, null).


2024-11-16 04:50:15,820 DEBG 'uvicorn-0' stdout output:
INFO:     172.30.227.7:0 - "POST /api/tasks?org=Farashenasa HTTP/1.0" 500 Internal Server Error

2024-11-16 04:50:16,764 DEBG 'uvicorn-1' stdout output:
INFO:     172.21.0.2:0 - "GET /api/auth/rules HTTP/1.0" 200 OK

2024-11-16 04:50:30,441 DEBG 'uvicorn-1' stdout output:
INFO:     172.21.0.2:0 - "GET /api/auth/rules HTTP/1.0" 304 Not Modified
```

**Comment by azadehashouri** [comment]
@bsekachev I solve the problem by reinstall CVAT from the first step.

But unfortunately I came across another problem. I want to restrict the download option for worker role. 
Could you check [this issue](https://github.com/cvat-ai/cvat/issues/8714) and help me if it's possible for you? Thanks a lot
