### ISSUE TITLE
export problem

### ISSUE THREAD

**Issue by Maradowei** [cvat-ai/cvat#8757]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Context

I failed to export approximately 97GB of data.
pottery.exceptions.ReleaseUnlockedLock: ('redlock:export_lock:/home/django/data/projects/5/export_cache/dataset-instance1732779070.857127-yolo-11.ZIP', frozenset({Redis<ConnectionPool<Connection<host=cvat_redis_inmem,port=6379,db=0>>>}))

**Comment by hyson1234567** [comment]
> Hi, please share the stack trace of the error, if possible. You can find it in the `cvat_worker_export` container logs right after the export (call `docker logs cvat_worker_export`) or in the admin panel - queues - export - failed jobs - your export job.
> 
> I assume that the file was too big, so the export job timeout was reached.

I can export small files without any issues, but when it comes to large files, such as 8GB ones, an error is reported


docker logs cvat_worker_export

[2025-11-04 01:15:58,383] ERROR rq.worker: [Job action=export&target=task&target_id=115&user_id=3&format=COCO_1~0&subresource=dataset]: exception raised while executing (cvat.apps.dataset_manager.views.export_task_as_dataset)
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/rq/worker.py", line 1431, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 1280, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.10/site-packages/rq/job.py", line 1317, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 233, in export_task_as_dataset
    return export(dst_format=dst_format, task_id=task_id, server_url=server_url, save_images=True)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 196, in export
    with get_export_cache_lock(
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/django/cvat/apps/dataset_manager/util.py", line 107, in get_export_cache_lock
    lock.release()
  File "/opt/venv/lib/python3.10/site-packages/pottery/redlock.py", line 595, in release
    raise ReleaseUnlockedLock(
pottery.exceptions.ReleaseUnlockedLock: ('redlock:export_lock:/home/django/data/cache/export/task-115-dataset-instance1761374461.201087-coco-10.zip', frozenset({Redis<ConnectionPool<Connection<host=cvat_redis_inmem,port=6379,db=0>>>}))

my version：2.43.0

**Comment by zhiltsov-max** [comment]
Hi,

CVAT takes locks by default for 30 seconds. Apparently, the [`move()`](https://github.com/cvat-ai/cvat/blob/57ceda9fc8b9cf8282dad9b0f54e4412012e5ae0/cvat/apps/dataset_manager/views.py#L201) call takes more than this. A simple solution could be increasing the `EXPORT_CACHE_LOCK_TTL` parameter to a bigger value by setting the `CVAT_EXPORT_CACHE_LOCK_TTL` environment variable. The value is in seconds, consider setting it to something like 300 seconds.
