### ISSUE TITLE
Issue with the sign in 

### ISSUE THREAD

**Issue by zoif2000** [cvat-ai/cvat#8800]
TypeError
o.map is not a function

TypeError: o.map is not a function
    at WV (http://localhost:8080/assets/cvat-ui.2550f8a90bec8e109359.min.js:2:9686912)
    at Ei (http://localhost:8080/assets/cvat-ui.2550f8a90bec8e109359.min.js:2:4885894)
    at Oa (http://localhost:8080/assets/cvat-ui.2550f8a90bec8e109359.min.js:2:4897475)
    at Ea (http://localhost:8080/assets/cvat-ui.2550f8a90bec8e109359.min.js:2:4896689)
    at Ca (http://localhost:8080/assets/cvat-ui.2550f8a90bec8e109359.min.js:2:4896303)
    at Es (http://localhost:8080/assets/cvat-ui.2550f8a90bec8e109359.min.js:2:4945702)
    at _c (http://localhost:8080/assets/cvat-ui.2550f8a90bec8e109359.min.js:2:4931630)
    at bc (http://localhost:8080/assets/cvat-ui.2550f8a90bec8e109359.min.js:2:4931558)
    at vc (http://localhost:8080/assets/cvat-ui.2550f8a90bec8e109359.min.js:2:4931421)
    at ic (http://localhost:8080/assets/cvat-ui.2550f8a90bec8e109359.min.js:2:4928256)
    
I try to open cvat for use with Chrome or Microsoft Edge browser, through the portle localhost:8080 as i was doing minutes before and suddenly the errors below occur : 
 **Could not send logs to the server

<html> <head><title>405 Not Allowed</title></head> <body> <center><h1>405 Not Allowed</h1></center> <hr><center>nginx</center> </body> </html>      **
or 
**Could not receive server schema**

Cannot convert undefined or null to object**
or
**Could not check authentication on the server

Open the Browser Console to get details**
or 
**Could not login on the server

Bad Gateway** (from console -> Failed to load resource: the server responded with a status of 502 (Bad Gateway))

CVAT version
Server:
Core: 15.3.0
Canvas: 2.20.10
UI: 1.67.0

**Comment by bsekachev** [comment]
Try to build the latest release without any modifications fisrt.
